name: Build and Upload Artifacts

on:
  push:
    branches:
      - master
      - 'ci-*'
      - 'stable*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - master
      - 'ci-*'
      - 'stable*'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-22.04, macos-13]
        include:
          - os: ubuntu-22.04
            docker_image: ubuntu:16.04
          - os: macos-13
            osx_image: xcode13.2

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup cache directory
        if: matrix.os == 'ubuntu-22.04'
        run: mkdir -p .cache/mailsync-build-deps-v2 .cache/opt-openssl

      - name: Cache build dependencies and opt directory
        if: matrix.os == 'ubuntu-22.04'
        uses: actions/cache@v3
        with:
          path: |
            .cache/mailsync-build-deps-v2
            .cache/opt-openssl
          key: ${{ matrix.os }}-mailsync-cache-${{ hashFiles('build.sh') }}
          restore-keys: |
            ${{ matrix.os }}-mailsync-cache-

      - name: Build in Docker (for ubuntu)
        if: matrix.os == 'ubuntu-22.04'
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ matrix.docker_image }}
          options: -v ${{ github.workspace }}:/workspace -v ${{ github.workspace }}/.cache/mailsync-build-deps-v2:/tmp/mailsync-build-deps-v2 -v ${{ github.workspace }}/.cache/opt-openssl:/opt/openssl
          run: |
            cd /workspace
            ./build.sh

      - name: Run build script (for macos)
        if: matrix.os == 'macos-13'
        run: ./build.sh

      - name: Upload artifact (Linux/macOS)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: mailsync-${{ github.sha }}-${{ runner.os }}.tar.gz
          path: app/dist/mailsync.tar.gz

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*
