name: Build and Upload Artifacts

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-22.04, macos-13, windows-2022]
        include:
          - os: ubuntu-22.04
            docker_image: ubuntu:16.04
          - os: macos-13
            osx_image: xcode13.2

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup cache directory
        if: matrix.os == 'ubuntu-22.04'
        run: mkdir -p .cache/mailsync-build-deps-v2 .cache/opt-openssl

      - name: Cache build dependencies and opt directory
        if: matrix.os == 'ubuntu-22.04'
        uses: actions/cache@v3
        with:
          path: |
            .cache/mailsync-build-deps-v2
            .cache/opt-openssl
          key: ${{ matrix.os }}-mailsync-cache-${{ hashFiles('build.sh') }}
          restore-keys: |
            ${{ matrix.os }}-mailsync-cache-

      - name: Build in Docker (for ubuntu)
        if: matrix.os == 'ubuntu-22.04'
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ matrix.docker_image }}
          options: -v ${{ github.workspace }}:/workspace -v ${{ github.workspace }}/.cache/mailsync-build-deps-v2:/tmp/mailsync-build-deps-v2 -v ${{ github.workspace }}/.cache/opt-openssl:/opt/openssl
          run: |
            cd /workspace
            ./build.sh

      - name: Run build script (for macos)
        if: matrix.os == 'macos-13'
        run: ./build.sh
        
      - name: Set up MSVC (for windows)
        if: matrix.os == 'windows-2022'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build with MSBuild (for windows)
        if: matrix.os == 'windows-2022'
        run: |
          cd Windows
          msbuild.exe mailsync.sln /property:Configuration=Release /property:Platform=Win32

      - name: Copy DLL dependencies and output (for windows)
        if: matrix.os == 'windows-2022'
        run: |
          New-Item -Path "app/dist" -ItemType Directory -Force
          Copy-Item -Path "Windows\Release\*" -Destination "app\dist" -Recurse -Force
          # Copy only the necessary modern runtime libraries. Old ones are not present on windows-2022.
          Copy-Item -Path "C:\Windows\SysWOW64\msvcp140.dll" -Destination "app\dist" -Force -ErrorAction SilentlyContinue
          Copy-Item -Path "C:\Windows\SysWOW64\vcruntime140.dll" -Destination "app\dist" -Force -ErrorAction SilentlyContinue
          Copy-Item -Path "C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x86\*" -Destination "app\dist" -Recurse -Force

      - name: Archive to mailsync.tar.gz (for windows)
        if: matrix.os == 'windows-2022'
        shell: powershell
        run: |
          Set-Location app/dist
          & "C:\Program Files\7-Zip\7z.exe" a -ttar mailsync.tar mailsync.exe *.dll *.pdb
          & "C:\Program Files\7-Zip\7z.exe" a -tgzip mailsync.tar.gz mailsync.tar

      - name: Upload artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: mailsync-${{ github.sha }}-${{ runner.os }}.tar.gz
          path: app/dist/mailsync.tar.gz

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Prepare release assets
        run: |
          cp artifacts/mailsync-*-Linux.tar.gz/mailsync.tar.gz mailsync-${{ github.ref_name }}-Linux.tar.gz
          cp artifacts/mailsync-*-Windows.tar.gz/mailsync.tar.gz mailsync-${{ github.ref_name }}-Windows.tar.gz
          cp artifacts/mailsync-*-macOS.tar.gz/mailsync.tar.gz mailsync-${{ github.ref_name }}-macOS.tar.gz

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            mailsync-${{ github.ref_name }}-Linux.tar.gz
            mailsync-${{ github.ref_name }}-Windows.tar.gz
            mailsync-${{ github.ref_name }}-macOS.tar.gz